name: Docker X-Build

on:
  push:
    branches: [master]
  schedule:
    - cron:  '0 22 * * *'

jobs:
  buildx:
    name: Build Base Images

    strategy:
      matrix:
        include:
          - image_base: buster
          - image_base: stretch-java
          - image_base: sid
          - image_base: ubuntu

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |-
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - name: Run Buildx
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t "proctorlabs/selfhosted-base:${{ matrix.image_base }}" --file "dockerfile.${{ matrix.image_base }}" --push .
